export ZSH=/home/dave/.oh-my-zsh

ZSH_THEME="dave"

plugins=(
  git
)

# load awesome-terminal-font scripts
source /usr/share/fonts/awesome-terminal-fonts/devicons-regular.sh
source /usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.sh
source /usr/share/fonts/awesome-terminal-fonts/octicons-regular.sh
source /usr/share/fonts/awesome-terminal-fonts/pomicons-regular.sh

source $ZSH/oh-my-zsh.sh

# copy pwd to xclip
alias cpwd="pwd | xclip"

# Git
alias gs="git status"
alias gb="git branch"
alias gba="git branch -a"

# launch sublime text in terminal
alias subl="/opt/sublime_text_3/sublime_text"

# open path in gui
alias open="/usr/bin/nautilus"

# launch jupyter-notebook
alias j="jupyter-notebook"

# added by Anaconda3 installer
export PATH="/home/dave/anaconda3/bin:$PATH"

# add vagrant path
export PATH="/home/dave/Downloads/vagrant_2.0.2_x86_64/opt/vagrant/bin:$PATH"

# remove vagrant ip from known_hosts
alias ckh="ssh-keygen -R 192.168.33.10; ssh-keygen -R localhost"
alias clean="grep -v "localhost" ~/.ssh/known_hosts > ~/.ssh/known_hosts.old; mv ~/.ssh/known_hosts.old
~/.ssh/known_hosts"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# needed for rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
